version: '3.3'
services:
    db:
        image: mysql:8.0
        container_name: db_lms
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_DB_NAME}
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - myNetwork

networks:
    myNetwork:

volumes:
    db_data:
