const authenRouter = require('./auth');
const modunRouter = require('./modun');
const courseRouter = require('./course');
const thematicRouter = require('./thematic');
const lessonRouter = require('./lesson');
const programRouter = require('./program');
const staffRouter = require('./staff');
const studentRouter = require('./student');
const teacherRouter = require('./teacher');
const majoringRouter = require('./majoring');
const gradeRouter = require('./grade');
const questionRouter = require('./question');
const examRouter = require('./exam');
const answerRouter = require('./answer');
const examQuestionRouter = require('./examquestion');
const exceprtRouter = require('./exceprt');
const syntheticCriteriaRouter = require('./syntheticcriteria');
const onlineCriteriaRouter = require('./onlinecriteria');
const modunCriteriaRouter = require('./moduncriteria');
const thematicCriteriaRouter = require('./thematiccriteria');
const dgnlCriteriaRouter = require('./dgnlcriteria');
const examTypeRouter = require('./examtype');
const selectedAnswerRouter = require('./selectedanswer');
const studentExamRouter = require('./studentexam');
const paymentRouter = require('./payment');
const documentRouter= require('./document');
const documentAdRouter = require('./documentad');
const courseAdRouter= require('./coursead');
const teacherCourseAdRouter=require('./teachercoursead');
const documentTypeRouter= require('./documenttype');
const menuRouter = require('./menu');
const menuTypeRouter = require('./menutype');
const courseDescriptionRouter=require('./coursedescription');
const dealerDiscountRouter=require('./dealerdiscount');
const detailedDiscountRouter=require('./detaileddiscount');
const discountCodeRouter=require('./discountcode');
const invoiceRouter = require('./invoice');
const detailedInvoiceRouter = require('./detailedinvoice');
const commentRouter = require('./comment');
const sideCommentRouter = require('./sidecomment');
const notificationRouter = require('./notification');
const accountBankRouter=require('./accountbank');
const footerRouter = require('./footer');
const contactRouter = require('./contact');
const courseStudentRouter = require('./coursestudent');
const provinceRouter = require('./province');
const evaluateRouter = require('./evaluate');
const dgnlEvaluateRouter = require('./dgnlevaluate');
const dgtdCriteriaRouter = require('./dgtdcriteria');
const dgtdEvaluateRouter = require('./dgtdevaluate');
const courseTypeRouter = require('./coursetype');

function route(app) {
    app.use('/auth', authenRouter);
    app.use('/course', courseRouter);
    app.use('/modun', modunRouter);
    app.use('/thematic', thematicRouter);
    app.use('/lesson', lessonRouter);
    app.use('/staff', staffRouter);
    app.use('/student', studentRouter);
    app.use('/teacher', teacherRouter);
    app.use('/program', programRouter);
    app.use('/major', majoringRouter);
    app.use('/grade', gradeRouter);
    app.use('/question', questionRouter);
    app.use('/exam', examRouter);
    app.use('/answer', answerRouter);
    app.use('/exam_question', examQuestionRouter);
    app.use('/exceprt', exceprtRouter);
    app.use('/synthetic_criteria', syntheticCriteriaRouter);
    app.use('/online_criteria', onlineCriteriaRouter);
    app.use('/modun_criteria', modunCriteriaRouter);
    app.use('/thematic_criteria', thematicCriteriaRouter);
    app.use('/dgnl-criteria', dgnlCriteriaRouter);
    app.use('/exam_type', examTypeRouter);
    app.use('/selected_answer', selectedAnswerRouter);
    app.use('/student_exam', studentExamRouter);
    app.use('/payment', paymentRouter);
    app.use('/document', documentRouter);
    app.use('/document_ad', documentAdRouter);
    app.use('/teachercourse_ad', teacherCourseAdRouter);
    app.use('/course_ad', courseAdRouter);
    app.use('/document_type', documentTypeRouter);
    app.use('/menu', menuRouter);
    app.use('/menu_type', menuTypeRouter);
    app.use('/course_description', courseDescriptionRouter);
    app.use('/dealer_discount',dealerDiscountRouter);
    app.use('/detailed_discount', detailedDiscountRouter);
    app.use('/discount_code', discountCodeRouter);
    app.use('/invoice', invoiceRouter);
    app.use('/detailed_invoice', detailedInvoiceRouter);
    app.use('/comment', commentRouter);
    app.use('/side_comment', sideCommentRouter);
    app.use('/notification', notificationRouter);
    app.use('/account_bank', accountBankRouter);
    app.use('/footer', footerRouter);
    app.use('/contact', contactRouter);
    app.use('/course_student', courseStudentRouter);
    app.use('/province', provinceRouter);
    app.use('/evaluate', evaluateRouter);
    app.use('/evaluate-dgnl', dgnlEvaluateRouter);
    app.use('/dgtd-criteria', dgtdCriteriaRouter);
    app.use('/evaluate-dgtd', dgtdEvaluateRouter);
    app.use('/course-type', courseTypeRouter);
}

module.exports = route;
