const authenRouter = require('./auth.route');
const modunRouter = require('./modun.route');
const courseRouter = require('./course.route');
const thematicRouter = require('./thematic.route');
const lessonRouter = require('./lesson.route');
const programRouter = require('./program.route');
const staffRouter = require('./staff.route');
const studentRouter = require('./student.route');
const teacherRouter = require('./teacher.route');
const majoringRouter = require('./majoring.route');
const gradeRouter = require('./grade.route');
const questionRouter = require('./question.route');
const examRouter = require('./exam.route');
const answerRouter = require('./answer.route');
const examQuestionRouter = require('./exam-question.route');
const exceprtRouter = require('./exceprt.route');
const syntheticCriteriaRouter = require('./synthetic-criteria.route');
const onlineCriteriaRouter = require('./online-criteria.route');
const modunCriteriaRouter = require('./modun-criteria.route');
const thematicCriteriaRouter = require('./thematic-criteria.route');
const dgnlCriteriaRouter = require('./dgnl-criteria.route');
const examTypeRouter = require('./exam-type.route');
const selectedAnswerRouter = require('./selected-answer.route');
const studentExamRouter = require('./student-exam.route');
const paymentRouter = require('./payment.route');
const documentRouter = require('./document.route');
const documentAdRouter = require('./document-ad.route');
const courseAdRouter = require('./course-ad.route');
const teacherCourseAdRouter = require('./teacher-course-ad.route');
const documentTypeRouter = require('./document-type.route');
const menuRouter = require('./menu.route');
const menuTypeRouter = require('./menu-type.route');
const courseDescriptionRouter = require('./course-description.route');
const dealerDiscountRouter = require('./dealer-discount.route');
const detailedDiscountRouter = require('./detailed-discount.route');
const discountCodeRouter = require('./discount-code.route');
const invoiceRouter = require('./invoice.route');
const detailedInvoiceRouter = require('./detailed-invoice.route');
const commentRouter = require('./comment.route');
const sideCommentRouter = require('./side-comment.route');
const notificationRouter = require('./notification.route');
const accountBankRouter = require('./account-bank.route');
const footerRouter = require('./footer.route');
const contactRouter = require('./contact.route');
const courseStudentRouter = require('./course-student.route');
const provinceRouter = require('./province.route');
const evaluateRouter = require('./evaluate.route');
const dgnlEvaluateRouter = require('./dgnl-evaluate.route');
const dgtdCriteriaRouter = require('./dgtd-criteria.route');
const dgtdEvaluateRouter = require('./dgtd-evaluate.route');
const courseTypeRouter = require('./course-type.route');
const examSetStudentRouter = require('./exam-set-student.route');
const positionRouter = require('./position.route');
const permissionRouter = require('./permission.route');
const departmentRouter = require('./department.route');

function route(app) {
    app.use('/auth', authenRouter);
    app.use('/course', courseRouter);
    app.use('/modun', modunRouter);
    app.use('/thematic', thematicRouter);
    app.use('/lesson', lessonRouter);
    app.use('/staff', staffRouter);
    app.use('/student', studentRouter);
    app.use('/teacher', teacherRouter);
    app.use('/program', programRouter);
    app.use('/major', majoringRouter);
    app.use('/grade', gradeRouter);
    app.use('/question', questionRouter);
    app.use('/exam', examRouter);
    app.use('/answer', answerRouter);
    app.use('/exam_question', examQuestionRouter);
    app.use('/exceprt', exceprtRouter);
    app.use('/synthetic_criteria', syntheticCriteriaRouter);
    app.use('/online_criteria', onlineCriteriaRouter);
    app.use('/modun_criteria', modunCriteriaRouter);
    app.use('/thematic_criteria', thematicCriteriaRouter);
    app.use('/dgnl-criteria', dgnlCriteriaRouter);
    app.use('/exam_type', examTypeRouter);
    app.use('/selected_answer', selectedAnswerRouter);
    app.use('/student_exam', studentExamRouter);
    app.use('/payment', paymentRouter);
    app.use('/document', documentRouter);
    app.use('/document_ad', documentAdRouter);
    app.use('/teachercourse_ad', teacherCourseAdRouter);
    app.use('/course_ad', courseAdRouter);
    app.use('/document_type', documentTypeRouter);
    app.use('/menu', menuRouter);
    app.use('/menu_type', menuTypeRouter);
    app.use('/course_description', courseDescriptionRouter);
    app.use('/dealer_discount', dealerDiscountRouter);
    app.use('/detailed_discount', detailedDiscountRouter);
    app.use('/discount_code', discountCodeRouter);
    app.use('/invoice', invoiceRouter);
    app.use('/detailed_invoice', detailedInvoiceRouter);
    app.use('/comment', commentRouter);
    app.use('/side_comment', sideCommentRouter);
    app.use('/notification', notificationRouter);
    app.use('/account_bank', accountBankRouter);
    app.use('/footer', footerRouter);
    app.use('/contact', contactRouter);
    app.use('/course_student', courseStudentRouter);
    app.use('/province', provinceRouter);
    app.use('/evaluate', evaluateRouter);
    app.use('/evaluate-dgnl', dgnlEvaluateRouter);
    app.use('/dgtd-criteria', dgtdCriteriaRouter);
    app.use('/evaluate-dgtd', dgtdEvaluateRouter);
    app.use('/course-type', courseTypeRouter);
    app.use('/examset-student', examSetStudentRouter);
    app.use('/position', positionRouter);
    app.use('/permission', permissionRouter);
    app.use('/department', departmentRouter);
}

module.exports = route;
